version: "2"
services:
  typecho:
    image: joyqi/typecho:1.2.1-php8.0-fpm
    restart: always
    environment:
      - TIMEZONE=Asia/Shanghai
      - MEMORY_LIMIT=100M
      - TYPECHO_SITE_URL=
    volumes:
      - ./usr:/app/usr

  nginx:
    image: nginx
    restart: always
    ports:
      - 80:80
    depends_on:
      - typecho
    volumes_from:
      - typecho
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
    environment:
      TZ: Asia/Shanghai
